config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :pages do
    collection do
      get :index
      post :chat
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end

  def chat
    message = params[:message]

    respond_to do |format|
      format.json do
        # response = ChatGpt::AssistantService.new.send_message(message)
        response = "ChatGpt::AssistantService.new.send_message(message)"
        render json: { message: response }
      end
      format.turbo_stream do
        # response = ChatGpt::AssistantService.new.send_message(message)
        response = "ChatGpt::AssistantService.new.send_message(message)2"
        render turbo_stream: turbo_stream.replace(
        "dialog-window",
        partial: "chat_message",
        locals: { message: response }
        )
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vector</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_chat_message.html.erb
<div class="border px-10 py-4 max-w-md w-max border-gray bg-slate-400 rounded-r-lg rounded-tl-lg self-start">
  <%= message %>
</div>

app/views/pages/index.html.erb
<div id="content" class="border w-full flex flex-col" data-controller="chat">
  <div data-chat-railsenv-value="<%= ENV.fetch('OPENAI_ACCESS_TOKEN') %>"></div>

  <div id="dialog-window" class="border border-green w-full h-96 flex flex-col overflow-y-scroll" data-chat-target="chatWindow">
    <!-- Chat messages will be added here -->
  </div>
  <div id="input-window" class="border border-red">
    <%= form_with url: chat_pages_path, class: 'flex w-full' do |form| %>
      <%= form.text_field :message, class: "w-full border-none", "data-chat-target": 'messageInput' %>
      <%= form.submit 'Send', class: "hover:bg-slate-300 hover:cursor-pointer", data: { action: 'click->chat#sendMessage' } %>
    <% end %>
  </div>
</div>